import { useMemo, useState } from 'react';
import { Calculator, Lightbulb } from 'lucide-react';
import { generateCalculation, withinTolerance } from '../services/calculations';
import { SourceRef } from '../components/SourceRef';
import { db } from '../db/db';
const options=[['moment','Moments'],['force','Force'],['pressure','Pressure'],['power','Power']] as const;
export function CalculationsPage(){
 const [formula,setFormula]=useState<string>('moment'); const [seed,setSeed]=useState(0); const problem=useMemo(()=>generateCalculation(formula),[formula,seed]); const [value,setValue]=useState('');const[hints,setHints]=useState(0);const[result,setResult]=useState<'correct'|'wrong'|''>('');
 const next=()=>{setSeed(x=>x+1);setValue('');setHints(0);setResult('');};
 const check=async()=>{const n=Number(value);const ok=Number.isFinite(n)&&withinTolerance(n,problem.expectedAnswer,problem.tolerance);setResult(ok?'correct':'wrong');await db.attempts.put({id:crypto.randomUUID(),questionId:problem.id,chapterId:'generated-practice',correct:ok,studentAnswer:value,createdAt:new Date().toISOString()});if(!ok)await db.mistakes.put({id:problem.id,questionId:problem.id,chapterId:'generated-practice',question:problem.prompt,studentAnswer:value,correctAnswer:`${problem.expectedAnswer} ${problem.expectedUnit}`,timesMissed:1,lastMissedDate:new Date().toISOString(),resolved:false});};
 return <div className="stack"><div className="page-title"><p className="eyebrow">Practice</p><h1>Calculation lab</h1><p>Generated practice uses verified textbook formulas. Each question is clearly labelled as generated.</p></div><div className="chip-row">{options.map(([id,label])=><button key={id} className={formula===id?'chip active':'chip'} onClick={()=>{setFormula(id);next();}}>{label}</button>)}</div><article className="calculation-card"><div className="generated-label"><Calculator size={17}/> Generated practice</div><h2>{problem.prompt}</h2><div className="known-grid">{problem.knownValues.map(v=><div key={v.symbol}><strong>{v.symbol}</strong><span>{v.value} {v.unit}</span></div>)}</div><label className="answer-input">Your numerical answer<input inputMode="decimal" value={value} onChange={e=>setValue(e.target.value)} placeholder="Enter a number"/></label><div className="button-row"><button className="primary-button" onClick={check}>Check answer</button><button className="secondary-button" onClick={()=>setHints(Math.min(problem.solutionSteps.length,hints+1))}><Lightbulb size={17}/> Hint {Math.min(hints+1,problem.solutionSteps.length)}</button></div>{hints>0&&<div className="hints">{problem.solutionSteps.slice(0,hints).map((h,i)=><p key={h}><strong>Hint {i+1}</strong> {h}</p>)}</div>}{result&&<div className={`result-box ${result}`}>{result==='correct'?`Correct. ${problem.expectedAnswer} ${problem.expectedUnit}`:`Not quite. Keep working or reveal more hints.`}</div>}<SourceRef pages={problem.sourcePages}/><button className="text-button" onClick={next}>New question</button></article></div>;
}
